# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MeasurePayload.pb

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MeasurePayload.pb',
  package='measure',
  syntax='proto3',
  serialized_pb=_b('\n\x11MeasurePayload.pb\x12\x07measure\"!\n\x03Tag\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"&\n\x08IntField\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"(\n\nFloatField\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"|\n\x0eMeasurePayload\x12\x1a\n\x04tags\x18\x01 \x03(\x0b\x32\x0c.measure.Tag\x12$\n\tintFields\x18\x02 \x03(\x0b\x32\x11.measure.IntField\x12(\n\x0b\x66loatFields\x18\x03 \x03(\x0b\x32\x13.measure.FloatFieldb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='measure.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='measure.Tag.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='measure.Tag.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=63,
)


_INTFIELD = _descriptor.Descriptor(
  name='IntField',
  full_name='measure.IntField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='measure.IntField.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='measure.IntField.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=103,
)


_FLOATFIELD = _descriptor.Descriptor(
  name='FloatField',
  full_name='measure.FloatField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='measure.FloatField.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='measure.FloatField.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=145,
)


_MEASUREPAYLOAD = _descriptor.Descriptor(
  name='MeasurePayload',
  full_name='measure.MeasurePayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tags', full_name='measure.MeasurePayload.tags', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intFields', full_name='measure.MeasurePayload.intFields', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatFields', full_name='measure.MeasurePayload.floatFields', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=271,
)

_MEASUREPAYLOAD.fields_by_name['tags'].message_type = _TAG
_MEASUREPAYLOAD.fields_by_name['intFields'].message_type = _INTFIELD
_MEASUREPAYLOAD.fields_by_name['floatFields'].message_type = _FLOATFIELD
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['IntField'] = _INTFIELD
DESCRIPTOR.message_types_by_name['FloatField'] = _FLOATFIELD
DESCRIPTOR.message_types_by_name['MeasurePayload'] = _MEASUREPAYLOAD

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
  DESCRIPTOR = _TAG,
  __module__ = 'MeasurePayload.pb_pb2'
  # @@protoc_insertion_point(class_scope:measure.Tag)
  ))
_sym_db.RegisterMessage(Tag)

IntField = _reflection.GeneratedProtocolMessageType('IntField', (_message.Message,), dict(
  DESCRIPTOR = _INTFIELD,
  __module__ = 'MeasurePayload.pb_pb2'
  # @@protoc_insertion_point(class_scope:measure.IntField)
  ))
_sym_db.RegisterMessage(IntField)

FloatField = _reflection.GeneratedProtocolMessageType('FloatField', (_message.Message,), dict(
  DESCRIPTOR = _FLOATFIELD,
  __module__ = 'MeasurePayload.pb_pb2'
  # @@protoc_insertion_point(class_scope:measure.FloatField)
  ))
_sym_db.RegisterMessage(FloatField)

MeasurePayload = _reflection.GeneratedProtocolMessageType('MeasurePayload', (_message.Message,), dict(
  DESCRIPTOR = _MEASUREPAYLOAD,
  __module__ = 'MeasurePayload.pb_pb2'
  # @@protoc_insertion_point(class_scope:measure.MeasurePayload)
  ))
_sym_db.RegisterMessage(MeasurePayload)


# @@protoc_insertion_point(module_scope)
